# ── base de datos local ───────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmania_db
spring.datasource.username=postgres
spring.datasource.password=1245

# ── JWT local ─────────────────────────────────────────────
jwt.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refreshToken.expiration=604800000

# ── mostrar SQL en local ──────────────────────────────────
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
